/* ============================================================================
   Migration 002: Patient Authentication + Predefined Appointment Slot System
   ----------------------------------------------------------------------------
   Firebird SQL - да се изврши со isql, flamerobin, или друг Firebird клиент
   врз базата конфигурирана во appsettings.json (ConnectionStrings:FirebirdConnection).

   ВАЖНО:
     - Направете BACKUP на базата пред да го извршите ова!
     - Скриптата претпоставува дека веќе постојат табелите USERS, PATIENTS,
       DOCTORS, APPOINTMENTS (со колона PARIENTID - историски typo, задржана
       заради компатибилност со постоечкиот код).
     - Имињата на CHECK constraint-ите (ROLE / STATUS) варираат според тоа
       како била креирана оригиналната база - проверете ги со прашањето подолу
       пред да ги извршите DROP CONSTRAINT линиите, и изменете ги имињата
       ако е потребно:

         SELECT rc.RDB$CONSTRAINT_NAME, rc.RDB$RELATION_NAME
         FROM RDB$RELATION_CONSTRAINTS rc
         WHERE rc.RDB$CONSTRAINT_TYPE = 'CHECK'
           AND rc.RDB$RELATION_NAME IN ('USERS', 'APPOINTMENTS');
   ============================================================================ */

SET TERM ^ ;

/* ---------------------------------------------------------------------------
   1) USERS - нови колони за е-пошта потврда и врска со пациент
   --------------------------------------------------------------------------- */
ALTER TABLE USERS ADD EMAIL VARCHAR(150)^
ALTER TABLE USERS ADD EMAILCONFIRMED BOOLEAN DEFAULT FALSE NOT NULL^
ALTER TABLE USERS ADD PATIENTID INTEGER^

/* Привремена вредност за постоечки редови (администратори/доктори без е-пошта) -
   Ве молиме изменете ги рачно со реални е-пошта адреси и потоа поставете EMAILCONFIRMED = TRUE. */
UPDATE USERS SET EMAIL = LOWER(USERNAME) || '@example.invalid' WHERE EMAIL IS NULL^
ALTER TABLE USERS ALTER COLUMN EMAIL SET NOT NULL^

/* Уникатност на е-пошта */
CREATE UNIQUE INDEX UX_USERS_EMAIL ON USERS (EMAIL)^

/* Странски клуч кон PATIENTS */
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_PATIENT
    FOREIGN KEY (PATIENTID) REFERENCES PATIENTS (ID)^

/* Дозволи ја новата улога "Patient" во CHECK constraint-от.
   ЗАМЕНЕТЕ ГО "CHK_USERS_ROLE" со реалното ime на constraint-от од Вашата база! */
-- ALTER TABLE USERS DROP CONSTRAINT CHK_USERS_ROLE^
ALTER TABLE USERS ADD CONSTRAINT CHK_USERS_ROLE
    CHECK (ROLE IN ('Administrator', 'Doctor', 'Patient'))^

/* ---------------------------------------------------------------------------
   2) APPOINTMENTS - PARIENTID сега смее да биде NULL (слободни слотови),
      и статусите се менуваат од Zakazan/Vo tek/Zavrsen/Otkazen во
      Free/Booked/Completed/Cancelled.
   --------------------------------------------------------------------------- */

/* Прво ги мигрираме постоечките вредности во новите статуси */
UPDATE APPOINTMENTS SET STATUS = 'Booked'    WHERE STATUS = 'Zakazan'^
UPDATE APPOINTMENTS SET STATUS = 'Booked'    WHERE STATUS = 'Vo tek'^
UPDATE APPOINTMENTS SET STATUS = 'Completed' WHERE STATUS = 'Zavrsen'^
UPDATE APPOINTMENTS SET STATUS = 'Cancelled' WHERE STATUS = 'Otkazen'^

/* Отстрани го стариот CHECK constraint за STATUS.
   ЗАМЕНЕТЕ ГО "CHK_APPOINTMENTS_STATUS" со реалното ime од Вашата база! */
-- ALTER TABLE APPOINTMENTS DROP CONSTRAINT CHK_APPOINTMENTS_STATUS^
ALTER TABLE APPOINTMENTS ADD CONSTRAINT CHK_APPOINTMENTS_STATUS
    CHECK (STATUS IN ('Free', 'Booked', 'Completed', 'Cancelled'))^

/* PARIENTID сега смее да биде NULL - слободните слотови немаат доделен пациент */
ALTER TABLE APPOINTMENTS ALTER COLUMN PARIENTID DROP NOT NULL^

/* ---------------------------------------------------------------------------
   3) EMAILCONFIRMATIONTOKENS - токени за потврда на е-пошта
   --------------------------------------------------------------------------- */
CREATE TABLE EMAILCONFIRMATIONTOKENS (
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERID      INTEGER NOT NULL,
    TOKEN       VARCHAR(64) NOT NULL,
    EXPIRESON   TIMESTAMP NOT NULL,
    CREATEDON   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_EMAILTOKENS_USER FOREIGN KEY (USERID) REFERENCES USERS (ID)
)^

CREATE UNIQUE INDEX UX_EMAILCONFIRMATIONTOKENS_TOKEN ON EMAILCONFIRMATIONTOKENS (TOKEN)^

SET TERM ; ^

/* ============================================================================
   По извршувањето:
     1. Проверете ги е-пошта адресите вметнати автоматски за постоечките
        Administrator/Doctor сметки (EMAIL колоната) и изменете ги со реални.
     2. За постоечките Administrator сметки, EMAILCONFIRMED си останува FALSE
        по default - рачно поставете EMAILCONFIRMED = TRUE за нив, инаку нема
        да можат да се најават (администраторските сметки не минуваат low
        registration flow):

          UPDATE USERS SET EMAILCONFIRMED = TRUE WHERE ROLE = 'Administrator';

     3. За постоечките Doctor сметки, или им испратете нов линк за потврда
        преку апликацијата, или исто така рачно поставете EMAILCONFIRMED = TRUE
        ако веќе се проверени доктори:

          UPDATE USERS SET EMAILCONFIRMED = TRUE WHERE ROLE = 'Doctor';
   ============================================================================ */
